SELECT * FROM jaegers;
SELECT * FROM jaegers WHERE status = 'false';
SELECT * FROM jaegers WHERE mark = 'Mark-1' AND 'Mark-4';
SELECT * FROM jaegers ORDER BY mark DESC;
SELECT MAX(launch) FROM jaegers;
SELECT MAX(kaijuKill) FROM jaegers;
SELECT MIN(kaijuKill) FROM jaegers;
SELECT AVG(weight) FROM jaegers;
UPDATE jaegers SET kaijuKill = kaijuKill + 1 WHERE status = 'false';
SELECT * FROM jaegers;
DELETE FROM jaegers WHERE status = 'false';